#! /usr/bin/bash
sudo apt-get install python-pip
sudo apt-get install python3.4
sudo apt-get install mercurial python3-dev python3-numpy libav-tools \
    libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev \
    libsdl1.2-dev  libportmidiS-dev libswscale-dev libavformat-dev libavcodec-dev \
    imagemagick graphicsmagick-imagemagick-compat
hg clone http://bitbucket.org/pygame/pygame
cd pygame
python3 setup.py build
sudo python3 setup.py install
cd ..
cp config ~
sudo chmod +x ./Tron.py
touch Lancer\ Tron
echo '#! /usr/bin/bash
python3 ./Tron.py' > Lancer\ Tron
